# Generated by Django 4.2.3 on 2023-07-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchDocumentsRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(blank=True, max_length=5000, null=True)),
                ("npm", models.CharField(blank=True, max_length=5000, null=True)),
                ("nama", models.CharField(blank=True, max_length=5000, null=True)),
                (
                    "judul_skripsi",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                (
                    "abstraksi_skripsi",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                ("similarity", models.FloatField(blank=True, null=True)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SpellingChecker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence", models.CharField(blank=True, max_length=5000, null=True)),
                (
                    "corrections",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TextSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text1", models.CharField(blank=True, max_length=5000, null=True)),
                ("text2", models.CharField(blank=True, max_length=5000, null=True)),
                ("cosine_similarity", models.FloatField(blank=True, null=True)),
                ("euclidean_distance", models.FloatField(blank=True, null=True)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
