# Generated by Django 4.2.3 on 2023-07-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kode", models.CharField(max_length=5, unique=True)),
                ("nama_agama", models.CharField(max_length=20)),
            ],
        ),
    ]
