# Generated by Django 4.2.3 on 2023-07-19 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crud_app_master", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agama",
            options={
                "verbose_name": "Data Agama",
                "verbose_name_plural": "List Data Agama",
            },
        ),
    ]
