# Generated by Django 4.2.3 on 2023-07-18 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("crud_app_master", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KategoriPegawai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kode", models.CharField(max_length=20, unique=True)),
                ("nama_kategori", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="StatusPegawai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kode", models.CharField(max_length=20, unique=True)),
                ("nama_status", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="BiodataPegawai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_deleted", models.DateTimeField(blank=True, null=True)),
                ("date_updated", models.DateTimeField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=50, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=50, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=50, null=True)),
                ("nip", models.CharField(max_length=20, unique=True)),
                ("nama", models.CharField(blank=True, max_length=200, null=True)),
                ("nik", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "tempat_lahir",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("tanggal_lahir", models.DateField(blank=True, null=True)),
                ("telepon", models.CharField(blank=True, max_length=20, null=True)),
                ("alamat", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "agama",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crud_app_master.agama",
                    ),
                ),
                (
                    "kategori",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crud_app.kategoripegawai",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crud_app.statuspegawai",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
