# Generated by Django 4.2.3 on 2023-07-19 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crud_app_master", "0002_alter_agama_options"),
        ("crud_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biodatapegawai",
            options={
                "verbose_name": "Data Pegawai",
                "verbose_name_plural": "List Data Pegawai",
            },
        ),
        migrations.AlterModelOptions(
            name="kategoripegawai",
            options={
                "verbose_name": "Kategori Pegawai",
                "verbose_name_plural": "List Kategori Pegawai",
            },
        ),
        migrations.AlterModelOptions(
            name="statuspegawai",
            options={
                "verbose_name": "Status Pegawai",
                "verbose_name_plural": "List Status Pegawai",
            },
        ),
        migrations.AddField(
            model_name="biodatapegawai",
            name="foto_identitas",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/identitas"
            ),
        ),
        migrations.AlterField(
            model_name="biodatapegawai",
            name="agama",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crud_app_master.agama"
            ),
        ),
        migrations.AlterField(
            model_name="biodatapegawai",
            name="kategori",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="crud_app.kategoripegawai",
            ),
        ),
        migrations.AlterField(
            model_name="biodatapegawai",
            name="nama",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="biodatapegawai",
            name="nik",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="biodatapegawai",
            name="nip",
            field=models.CharField(max_length=20, unique=True, verbose_name="NIP"),
        ),
        migrations.AlterField(
            model_name="biodatapegawai",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crud_app.statuspegawai"
            ),
        ),
        migrations.AlterField(
            model_name="biodatapegawai",
            name="tanggal_lahir",
            field=models.DateField(),
        ),
    ]
